### ISSUE TITLE
Baidu link broken

### ISSUE THREAD

**Issue by pranavpawar3** [junqiangchen/HC18-Automated-measurement-of-fetal-head-circumference#4]
Hey, 

I am trying to download the masked annotation images from the Baidu link you have given, but I am unable to do so. Can you share a google drive link for the same?

> convert annotation image to mask image, you can download here:https://pan.baidu.com/s/1NmmztKR0Omu1fKue7263Sw password：6ax7

This part.

**Comment by junqiangchen** [comment]
> Hey,
> I am trying to download the masked annotation images from the Baidu link you have given, but I am unable to do so. Can you share a google drive link for the same?
> 
> convert annotation image to mask image, you can download here:https://pan.baidu.com/s/1NmmztKR0Omu1fKue7263Sw password：6ax7
> 
> This part.
Hi,
i only share the dataset on baidu cloud disk in china,i can't use goodle drive link to share it.i am sorry.
thank you!

**Comment by zhang326905612** [comment]
可以再发下百度云链接吗  不懂这个数据csv文件啥意思

**Comment by junqiangchen** [comment]
可以邮件联系我一下
